name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies in the 'NuxtTest' directory
      - name: Install dependencies
        working-directory: ./NuxtTest
        run: npm install

      # Build and generate static files
      - name: Build and Generate Static Files
        working-directory: ./NuxtTest
        env:
          NUXT_SSR: false
          NUXT_TARGET: static
        run: npm run generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./NuxtTest/dist
