name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Go to the correct project folder if it's in a subdirectory, else leave as default
      - name: Install dependencies
        working-directory: ./nuxt-test # Use only if your project is in 'nuxt-test' subfolder
        run: npm install

      - name: Build and Generate Static Files
        working-directory: ./nuxt-test # Same as above, adjust if needed
        env:
          NUXT_SSR: false
          NUXT_TARGET: static
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nuxt-test/dist # Set this based on the actual build output location
